config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :relevances
  resources :wish_progresses
  resources :wishes
  get 'welcome/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
end

app/models/relevance.rb
class Relevance < ApplicationRecord

	has_many :wish_progress
end

app/controllers/relevances_controller.rb
class RelevancesController < ApplicationController
  before_action :set_relevance, only: [:show, :edit, :update, :destroy]

  # GET /relevances
  # GET /relevances.json
  def index
    @relevances = Relevance.all
  end

  # GET /relevances/1
  # GET /relevances/1.json
  def show
  end

  # GET /relevances/new
  def new
    @relevance = Relevance.new
  end

  # GET /relevances/1/edit
  def edit
  end

  # POST /relevances
  # POST /relevances.json
  def create
    @relevance = Relevance.new(relevance_params)

    respond_to do |format|
      if @relevance.save
        format.html { redirect_to @relevance, notice: 'Relevance was successfully created.' }
        format.json { render :show, status: :created, location: @relevance }
      else
        format.html { render :new }
        format.json { render json: @relevance.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relevances/1
  # PATCH/PUT /relevances/1.json
  def update
    respond_to do |format|
      if @relevance.update(relevance_params)
        format.html { redirect_to @relevance, notice: 'Relevance was successfully updated.' }
        format.json { render :show, status: :ok, location: @relevance }
      else
        format.html { render :edit }
        format.json { render json: @relevance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relevances/1
  # DELETE /relevances/1.json
  def destroy
    @relevance.destroy
    respond_to do |format|
      format.html { redirect_to relevances_url, notice: 'Relevance was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relevance
      @relevance = Relevance.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relevance_params
      params.require(:relevance).permit(:description, :value)
    end
end

app/helpers/relevances_helper.rb
module RelevancesHelper
end

app/views/relevances/_form.html.erb
<%= form_with(model: relevance, local: true) do |form| %>
  <% if relevance.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relevance.errors.count, "error") %> prohibited this relevance from being saved:</h2>

      <ul>
      <% relevance.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :relevance_description %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :relevance_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/relevances/edit.html.erb
<h1>Editing Relevance</h1>

<%= render 'form', relevance: @relevance %>

<%= link_to 'Show', @relevance %> |
<%= link_to 'Back', relevances_path %>

app/views/relevances/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relevances</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relevances.each do |relevance| %>
      <tr>
        <td><%= relevance.description %></td>
        <td><%= link_to 'Show', relevance %></td>
        <td><%= link_to 'Edit', edit_relevance_path(relevance) %></td>
        <td><%= link_to 'Destroy', relevance, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relevance', new_relevance_path %>

app/views/relevances/new.html.erb
<h1>New Relevance</h1>

<%= render 'form', relevance: @relevance %>

<%= link_to 'Back', relevances_path %>

app/views/relevances/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @relevance.description %>
</p>

<%= link_to 'Edit', edit_relevance_path(@relevance) %> |
<%= link_to 'Back', relevances_path %>