config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :relevances
  resources :wish_progresses
  resources :wishes
  get 'welcome/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
end

app/models/wish.rb
class Wish < ApplicationRecord

	belongs_to :user
	has_many :goal, dependent: :destroy
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :set_wish, only: [:show, :edit, :update, :destroy]

  # GET /wishes
  # GET /wishes.json
  def index
    @wishes = Wish.where(user:current_user.id).all
   
  end

  # GET /wishes/1
  # GET /wishes/1.json
  def show
  end

  # GET /wishes/new
  def new
    @wish = Wish.new
  end

  # GET /wishes/1/edit
  def edit
  end

  # POST /wishes
  # POST /wishes.json
  def create
    @wish = Wish.new(wish_params)
    @wish.user = current_user
    respond_to do |format|
      if @wish.save
        format.html { redirect_to @wish, notice: 'Wish was successfully created.' }
        format.json { render :show, status: :created, location: @wish }
      else
        format.html { render :new }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishes/1
  # PATCH/PUT /wishes/1.json
  def update
    respond_to do |format|
      if @wish.update(wish_params)
        format.html { redirect_to @wish, notice: 'Wish was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish }
      else
        format.html { render :edit }
        format.json { render json: @wish.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishes/1
  # DELETE /wishes/1.json
  def destroy
    @wish.destroy
    respond_to do |format|
      format.html { redirect_to wishes_url, notice: 'Wish was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish
      @wish = Wish.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_params
      params.require(:wish).permit(:title, :description, :initDate, :endDate)
    end
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/wishes/_form.html.erb
<%= form_with(model: wish, local: true) do |form| %>
  <% if wish.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish.errors.count, "error") %> prohibited this wish from being saved:</h2>

      <ul>
      <% wish.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   
  
  
  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :wish_title, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :wish_description, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :initDate %>
    <%= form.date_select :initDate, id: :wish_initDate, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :endDate %>
    <%= form.date_select :endDate, id: :wish_endDate, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.submit  :class =>'btn btn-primary' %>
  </div>
<% end %>

app/views/wishes/edit.html.erb
<h1>Editing Wish</h1>

<%= render 'form', wish: @wish %>

<%= link_to 'Show', @wish %> |
<%= link_to 'Back', wishes_path %>

app/views/wishes/index.html.erb
<ul class="nav">
  <li class="nav-item">
   <%= link_to 'My progress', wish_progresses_path, :class => 'nav-link active' %>
   <%= link_to 'My Goals', goals_path, :class => 'nav-link active' %>
  </li>
</ul>

<p id="notice"><%= notice %></p>

<h1>Wishes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Init at</th>
      <th>End at</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishes.each do |wish| %>
      <tr>
        <td><%= link_to wish.title, wish %></td>
        <td><%= wish.description %></td>
        <td><%= wish.initDate.strftime('%d/%m/%Y') %></td>
        <td><%= wish.endDate.strftime('%d/%m/%Y') %></td>
        <td><a href="/wish_progresses/new?wish_id=<%= wish.id%>">Add progresso 
        <span class="badge badge-primary badge-pill"> <%=wish.goal.length %></span></a></td>
        <td><%= link_to 'Show', wish %><span class="fi-plus"></span></td>
        <td><%= link_to 'Edit', edit_wish_path(wish) %></td>
        <td><%= link_to 'Destroy', wish, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

     
    <% end %>
  </tbody>
</table>

<br>

<div class="row" style="float:right;">
<%= link_to 'Criar novo Wish ', new_wish_path, :class=> 'btn btn-primary', :style=>"float:right" %>
</div>

app/views/wishes/new.html.erb
<h1>New Wish</h1>

<%= render 'form', wish: @wish %>

<%= link_to 'Back', wishes_path %>

app/views/wishes/show.html.erb
<style type="text/css">
  
  .wish-progress-list-wrapper{
    display: none;
    margin-top: 10px;
  }
</style>

<p id="notice"><%= notice %></p>
<h2 class="header">
  <%= @wish.title %>
</h2>

<div class="progress-wrapper" style="float:left;">

<p>
  <strong>Description:</strong>
  <%= @wish.description %>
</p>

<p>
  <strong>Init at:</strong>
  <%= @wish.initDate.strftime('%d/%m/%Y') %> to <%= @wish.endDate.strftime('%d/%m/%Y') %>
</p>


  <% if !@wish.goal.empty? %>

    <p>Your work</p>

    <ul class="list-group">

       <% @wish.goal.each do |goal| %>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          <div style="width:100%; height:auto; overflow:hidden; ">
            <a href="#" class="goal-title"><%=goal.name%></a>
            <span class="badge badge-primary badge-pill"><%=goal.wish_progress.length%></span>

            <div class="wish-progress-list-wrapper">
            <ul class=""> 
              <% goal.wish_progress.each do |wish_progress| %>
                <li> <%=wish_progress.description %> - (<%=wish_progress.relevance.value%>/<%=wish_progress.goal.points%>)</li>
              <% end %>
              </ul>

              <ul class="nav">
                  <li>
                       <%= link_to 'Edit goal', edit_goal_path, :class => 'btn btn-default' %> 
                  </li>

                  <li>
                       <%= link_to 'Add progress', new_wish_progress_path, :class => 'btn btn-default' %> 
                  </li>
              </ul>
            </div>
          </div>
        </li>
    </ul> 
  <% end %>

  <% if @wish.goal.blank %>
    <h1></h1>
  <% end %>


 </div>


<% @list = @wish.goal.map{|k| "'#{k.name}'"}.join(",") %>
<% @points = @wish.goal.map{|k| k.points}.join(",") %>

<%

    map = {}
    @wish.goal.each do |goal|

      map[goal] = 0
      goal.wish_progress.each do |wp|
      
        map[goal] = map[goal]+wp.relevance.value
        
      end
    end
%>

<% @myPoints = map.map{|k,v| v}.join(",") %>

<div id="canvas-wrapper" style="width:500px; height:500px; float:right">
<canvas id="myChart" width="200" height="200"></canvas>
</div>

<script type="text/javascript">
var ctx = document.getElementById("myChart");
var myChart = new Chart(ctx, {
    type: 'radar',
    data: {
        
        labels:  [ <%=raw @list %>],
        datasets: [{
            label: 'Your goals',
            data:  [<%=raw @points %>],
            borderColor: "#ccc000"
        }, {

          data: [<%=@myPoints%>],
          borderColor: "#82e06d",
          label: "Your current progress"
        }],
        
        borderWidth: 0.5
    },
     options: {
        
    }
});
</script>
<% end %>


<div class="action-wrapper" style="clear:both">
<a href="/wish_progresses/new?wish_id=<%= @wish.id%>" class="btn btn-primary">Add progresso </a>
<%= link_to 'Edit', edit_wish_path(@wish), :class=> "btn btn-success" %> 
<%= link_to 'Back', wishes_path, :class=> "btn btn-default" %>
</div>


<script type="text/javascript">
jQuery(document).ready(function(){

  jQuery('a.goal-title').click(function(e){

    jQuery(e.currentTarget).parent().find('.wish-progress-list-wrapper').toggle();

    e.preventDefault();
  })
})

</script>