config/routes.rb
Rails.application.routes.draw do
  resources :goals
  resources :relevances
  resources :wish_progresses
  resources :wishes
  get 'welcome/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "welcome#index"
end

app/controllers/wish_progresses_controller.rb
class WishProgressesController < ApplicationController
  before_action :set_wish_progress, only: [:show, :edit, :update, :destroy]

  # GET /wish_progresses
  # GET /wish_progresses.json
  def index
    @wish_progresses = WishProgress.all
  end

  # GET /wish_progresses/1
  # GET /wish_progresses/1.json
  def show
  end

  # GET /wish_progresses/new
  def new
    @wish_progress = WishProgress.new
  end

  # GET /wish_progresses/1/edit
  def edit
  end

  # POST /wish_progresses
  # POST /wish_progresses.json
  def create
    # wish = Wish.find(params[:wish][:wish_id])
    @wish_progress = WishProgress.new(wish_progress_params)
    # @wish_progress.wish = wish
    respond_to do |format|
      if @wish_progress.save
        format.html { redirect_to @wish_progress.goal.wish, notice: 'Wish progress was successfully created.' }
        format.json { render :show, status: :created, location: @wish_progress }
      else
        format.html { render :new }
        format.json { render json: @wish_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCPATCHH/PUT /wish_progresses/1
  # PATCH/PUT /wish_progresses/1.json
  def update
    respond_to do |format|
      if @wish_progress.update(wish_progress_params)
        



        format.html { redirect_to @wish_progress, notice: 'Wish progress was successfully updated.' }
        format.json { render :show, status: :ok, location: @wish_progress }
      else
        format.html { render :edit }
        format.json { render json: @wish_progress.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wish_progresses/1
  # DELETE /wish_progresses/1.json
  def destroy
    @wish_progress.destroy
    respond_to do |format|
      format.html { redirect_to wish_progresses_url, notice: 'Wish progress was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wish_progress
      @wish_progress = WishProgress.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wish_progress_params
      params.require(:wish_progress).permit(:description, :dataRegistro, :goal_id, :relevance_id)
    end
end

app/helpers/wish_progresses_helper.rb
module WishProgressesHelper
end

app/views/wish_progresses/_form.html.erb
<%= form_with(model: wish_progress, local: true) do |form| %>
  <% if wish_progress.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wish_progress.errors.count, "error") %> prohibited this wish_progress from being saved:</h2>

      <ul>
      <% wish_progress.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    
  <%= 
     form.select :goal_id, 
    Goal.joins(:wish).where(wishes: {user:current_user}).collect{|goal| [goal.name, goal.id]}

  %>

  </div>


  <div class="field form-group">
    <%= form.label :relecance_id %>
    
    <%= form.select :relevance_id, Relevance.all.collect { |user| [user.description, user.id] } %>
 
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, id: :wish_progress_description, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :dataRegistro %>
    <%= form.date_select :dataRegistro, id: :wish_progress_dataRegistro, :class =>'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.submit  :class =>'btn btn-primary'%>
  </div>
<% end %>

app/views/wish_progresses/edit.html.erb
<h1>Editing Wish Progress</h1>

<%= render 'form', wish_progress: @wish_progress %>

<%= link_to 'Show', @wish_progress %> |
<%= link_to 'Back', wish_progresses_path %>

app/views/wish_progresses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wish Progresses</h1>

<table>
  <thead>
    <tr>
      <th>Wish</th>
      <th>Description</th>
      <th>Dataregistro</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wish_progresses.each do |wish_progress| %>
      <tr>
        <td><%= wish_progress.goal %></td>
        <td><%= wish_progress.description %></td>
        <td><%= wish_progress.dataRegistro %></td>
        <td><%= link_to 'Show', wish_progress %></td>
        <td><%= link_to 'Edit', edit_wish_progress_path(wish_progress) %></td>
        <td><%= link_to 'Destroy', wish_progress, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wish Progress', new_wish_progress_path %>

app/views/wish_progresses/new.html.erb
<h1>New Wish Progress</h1>

<%= render 'form', wish_progress: @wish_progress %>

<%= link_to 'Back', wish_progresses_path %>

app/views/wish_progresses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Goal:</strong>
  <%= @wish_progress.relevance.value %> / <%= @wish_progress.goal.points %> 
</p>


<p>
  <strong>Description:</strong>
  <%= @wish_progress.description %>
</p>

<p>
  <strong>Dataregistro:</strong>
  <%= @wish_progress.dataRegistro %>
</p>

<%= link_to 'Edit', edit_wish_progress_path(@wish_progress) %> |
<%= link_to 'Back', wish_progresses_path %>